### PR TITLE
Update cpi release links, stemcell versions v250.17, bpm version with workable links and sha1

### PR DESCRIPTION
**Pull request by xiujiao**

### CODE REVIEW

**Comment by jhunt** [comment]
The bosh.io links for stemcells (i.e. https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=250.17) redirect to the correct S3 resource; is there a reason we are trying to go direct?

**Comment by xiujiao** [comment]
@jhunt The sha1 in bosh.io one does not match what they have in the online doc here : https://bosh.cloudfoundry.org/stemcells/bosh-aws-xen-hvm-ubuntu-xenial-go_agent
the s3 resource matches the sha1 they listed on the website. You do remind me a good point, in the case they change where they store the stemcell but keep the bosh.io link, then it will break our kit. Maybe a better solution is to keep the bosh.io link, updated the sha1 instead?

**Comment by jhunt** [comment]
Yeah, it's a mess.  Have we reported the problem back upstream to bosh.io?

**Comment by xiujiao** [comment]
found this when I tried to report the issue https://github.com/bosh-io/web/issues/39
Based on the above information, I rolled back to use the bosh.io link, but for the IaaS (AWS, GCP) which has light stemcells, I used the light stemcell sha1 instead to make it work with the link

**Pull request merged**
