### PR TITLE
Add ssh user: osop

### PR DESCRIPTION
**Pull request by xiujiao**
Should solve issue https://github.com/genesis-community/bosh-genesis-kit/issues/23

### CODE REVIEW

**Comment by xiujiao** [comment]
@jhunt Do you mean adding password on the same `sysop` user?
I had to two users since it does not allow us set both ssh and password on one user
`/bosh-release-job356313730/templates/pre-start.sh.erb' for user_add/0 (line 23: #<RuntimeError: User: 'sysop' is configured with both 'crypted_password' and 'public_key'. Choose one.>) (RuntimeError)`
However, adding two users does not work fully yet, after adding two users I can ssh with private key, but I could not enable password login

**Comment by jhunt** [comment]
That sounds like a deficiency in the os-conf-release.  Perhaps we should address that shortcoming there?

**Comment by jhunt** [comment]
see https://github.com/cloudfoundry/os-conf-release/issues/13

**Comment by xiujiao** [comment]
Changed user name to sysop, leave the PR with adding  a ssh user only, since
1) User auth is disabled by default in sshd_config. See related PR here https://github.com/cloudfoundry/os-conf-release/pull/8
2) One user can not have both ssh and pass auth configured at the same time in the release
James has commented in the issue regarding to 2) and bumped in PR in 1)
Now we wait for the repo maintainer's response on those

**Pull request closed without merging**
